### ISSUE TITLE
Unable to store Job : 'DEFAULT.QueueMonitorJob', because one already exists with this identification. 

### ISSUE THREAD

**Issue by gus-romero** [kuhnza/thundr-contrib-deferred#2]
**Original issue for reference**
https://github.com/3wks/thundr/issues/16

Hey, I'm having this issue while running a Tomcat 7 Application on Elastic Beanstalk. This happens every time I try to deploy the app.

**App config**: ```64bit Amazon Linux 2016.09 v2.5.5 running Tomcat 7 Java 7```

**Java Stack trace**: 
```
ERROR thundr - Unable to store Job : 'DEFAULT.QueueMonitorJob', because one already exists with this identification.
2017-06-15T20:39:03.012Z ERROR [ThundrServlet] - Allocate exception for servlet ThundrServlet
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.QueueMonitorJob', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:277) ~[quartz-2.1.7.jar:na]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:249) ~[quartz-2.1.7.jar:na]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:840) ~[quartz-2.1.7.jar:na]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:250) ~[quartz-2.1.7.jar:na]
	at com.threewks.thundr.quartz.QuartzScheduler.scheduleJob(QuartzScheduler.java:184) ~[thundr-contrib-quartz-0.1.0.jar:na]
	at com.threewks.thundr.deferred.monitor.quartz.QuartzQueueMonitor.start(QuartzQueueMonitor.java:53) ~[thundr-contrib-deferred-0.1.0.jar:na]
	at com.threewks.thundr.deferred.DeferredModule.start(DeferredModule.java:50) ~[thundr-contrib-deferred-0.1.0.jar:na]
	at com.threewks.thundr.module.Modules.startNext(Modules.java:145) ~[thundr-1.1.1.jar:na]
	at com.threewks.thundr.module.Modules.runStartupLifecycle(Modules.java:97) ~[thundr-1.1.1.jar:na]
	at com.threewks.thundr.ThundrServlet.initModules(ThundrServlet.java:89) ~[thundr-1.1.1.jar:na]
	at com.threewks.thundr.ThundrServlet.init(ThundrServlet.java:64) ~[thundr-1.1.1.jar:na]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:853) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.75]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.75]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683) [catalina.jar:7.0.75]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) [catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.75]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) [catalina.jar:7.0.75]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087) [tomcat-coyote.jar:7.0.75]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) [tomcat-coyote.jar:7.0.75]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote.jar:7.0.75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_131]
```

Update info:

I found that the EC2 environment is running tomcat daemon
is it possible that the RAMJobStore is still alive after a 
```/etc/init.d/tomcat7 stop```

**Comment by kuhnza** [comment]
Thanks for bringing that to my attention @gus-romero. Truth be told I haven't run this up in quite some time (most of my stuff is on Google App Engine these days). 

What version of Thundr are you running this on? The lib probably needs a bump to bring it up to compatibility with later versions. 

From the look of the stack trace I suspect the problem lies in [thundr-contrib-quartz](https://github.com/kuhnza/thundr-contrib-quartz) which hasn't been updated in quite a while either. 

If I were taking a wild ass guess I'm thinking that you're probably on a newer version of Thundr (i.e. > 1.0) and that the shutdown hook isn't being called in the Quartz module. From memory the servlet lifecycle stuff all changed in Thundr 2.0 which might explain the issue.

**Comment by gus-romero** [comment]
Hi, I found that this is triggered by other exception, I have not dug enough, but it looks like its not an error from the thundr-contrib-deferred code. I will close since now its working, the error was related to Elastic Search instances that were no running. If I find evidence that this is related to thundr-contrib-deferred, I'll reopen with more information. Thank you
